main:
  push:
    # 生成 CodeWiki 文档
    - services:
        - docker
      docker:
        volumes:
          - /data/codewiki/${CNB_REPO_SLUG}:data
      stages:
        - name: generate codewiki
          timeout: 10h
          image: cnbcool/codewiki:latest
          settings:
            git_doc_dir: /data/codewiki/${CNB_REPO_SLUG}

$:
  push:
    # 导入密钥仓库文件为环境变量
    - imports:
        - https://cnb.cool/liweijie0812/secret/-/blob/main/token.yml
      stages:
        - name: sync to github with rebase
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/liweijie0812/tdesign-skills
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}

  vscode:
    - docker:
        build: .cnb/Dockerfile
      services:
        - vscode
        - docker
      stages:
        - name: clone tdesign repo
          jobs:
            - name: clone tdesign-common
              script:
                - cd /
                - git clone https://github.com/Tencent/tdesign-common.git --depth=1

            - name: clone tdesign-vue-next
              script:
                - cd /
                - git clone https://github.com/Tencent/tdesign-vue-next.git --depth=1

            - name: clone tdesign-vue
              script:
                - cd /
                - git clone https://github.com/Tencent/tdesign-vue.git --depth=1

            - name: clone tdesign-react
              script:
                - cd /
                - git clone https://github.com/Tencent/tdesign-react.git --depth=1

            - name: clone tdesign-mobile-vue
              script:
                - cd /
                - git clone https://github.com/Tencent/tdesign-mobile-vue.git --depth=1

            - name: clone tdesign-mobile-react
              script:
                - cd /
                - git clone https://github.com/Tencent/tdesign-mobile-react.git --depth=1

            - name: clone tdesign-miniprogram
              script:
                - cd /
                - git clone https://github.com/Tencent/tdesign-miniprogram.git --depth=1
          
            - name: clone tdesign-icons
              script:
                - cd /
                - git clone https://github.com/Tencent/tdesign-icons.git --depth=1
  
